### ISSUE TITLE
Cyrillic symbols support

### ISSUE THREAD

**Issue by filipovskis** [Earu/gm_win_toast#2]
![Image](https://i.imgur.com/qGD4OhO.png)
`WinToast.Show("Server", "Привет")`

**Comment by Earu** [comment]
Fixed in https://github.com/Earu/gm_win_toast/commit/1d03c1efcc42126479e85e9403b9a018a73f1c2d

**Comment by Earu** [comment]
Do note you'll have to compile the new version yourself
